### ISSUE TITLE
Add a Primer tab for Phase 6

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/scoreboard#13]
Currently [Desmos Primer Phase 6](https://primer.desmos.network/phase-6/) is running. For this reason, we should create a new tab inside the view to make sure that its data are displayed properly.

### Query
The query to be used is the following

```graphql
query Phase6 {
  primer_phase_6 {
    block_unblocked_user
    changed_dtag
    created_relationships
    edited_post
    transferred_dtag
    username
  }
}
```

### Rewards
The associated rewards are: 
- Block & Unblock a user: **50 DSM**
- Change DTag: **25 DSM**
- Create relationship: **25 DSM**
- Edit post: **50 DSM**
- Transfer DTag: **100 DSM**

**Comment by ryuash** [comment]
@YuhsinLiao1995 Give this a try
