### ISSUE TITLE
Bug in per-user rewards computation

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/scoreboard#17]
## Description
On Discord a user reported that it seems like there is a bug inside the rewards computation process.

## How to reproduce
1. Open the per-user total view ([_Users_](https://scoreboard.desmos.network/users)).
2. Order the rows by *DSM gained*  in a descending fashion (double click on *DSM gained*. 
3. Look at KalpaTech amount. It should be `12,535`. 
4. Refresh the page. 
5. Order the rows by *DSM gained*  in a descending fashion again (double click on *DSM gained*. 
6. Look at KalpaTech amount. It is now `18,535`.

The difference is exactly `6,000` which is the Validating Summer amount.

**Comment by ryuash** [comment]
Let me know if something similar happens again. Should've been fixed in my testing PR
